import type { Metadata } from "next";
import localFont from "next/font/local";
import "./styles/globals.css";
import * as ui from "./ui"

const geistSans = localFont({
  src: "./assets/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./assets/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Ernesto Fava",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="es">
      <head>
        <link rel="icon" href="/icon.svg" type="image/svg+xml" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} 
      antialiased block justify-center items-center min-w-80 
      md:container md:mx-auto md:px-24 md:grid md:gap-3 md:py-8 lg:gap-0 
      lg:h-screen lg:flex lg:overflow-hidden`
      } >

        <nav className="relative z-10 lg:w-1/3 lg:max-w-md xl:2/5">
          <ui.navbar />
          <ui.profile />
        </nav>

        <main className="relative 
        lg:w-3/5 lg:-ms-1.5 lg:overflow-auto lg:h-[30rem] 
        xl:w-1/2 xl:h-[36rem] 
        2xl:h-[40rem]"
        >
          {children}
        </main>
        
        <ui.background />

      </body>
    </html>
  );
}
